# Generated by Django 4.2.23 on 2025-11-18 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='label',
        ),
    ]
